stages: 
  - deploy

deploy:
  image: ruby
  stage: deploy
  # only: 
  #   - main
  script: 
    - gem install dpl
    - dpl --provider=heroku --app=lumensoutenance --api_key=d7d94b18-625f-401d-bda4-7a5402dbd75d
